### ISSUE TITLE
I have one question in code running.

### ISSUE THREAD

**Issue by yucenshen** [kundajelab/DeepBindToKeras#1]
when I running code `model = convert_model(file_name = file_name, input_len=38)`,compiler give me a bug text `pad() got an unexpected keyword argument 'constant_values'`.
How to solve the problem?
Thanks!!

**Comment by AvantiShri** [comment]
Are you using the latest tensorflow version? constant_values is part of the latest tensorflow API: https://www.tensorflow.org/api_docs/python/tf/pad

Also, hello! How did you find this repository?

**Comment by rouanshen** [comment]
Thank you for your response. I'm a master student in Taiwan.
I am also interested in DeepBind,I want to put more sequences in there. So, I hope you can open training code with keras for me.
E-mail: ambershen0222@gmail.com
